services:
  n8n:
    image: n8nio/n8n:latest
    container_name: curetrack-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      TZ: Europe/Paris
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - curetrack-network

  curetrack-db:
    image: postgres:16
    container_name: curetrack-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - curetrack-network

volumes:
  pgdata:

networks:
  curetrack-network:
    driver: bridge
